/* 
  Daisy Barajas 
  CS 121 
  30 October 2023 
  Program a game of rock, paper, scissors where the user plays against the computer. 
*/ 

#include <iostream>
#include <cctype> 
#include <cstdlib>
#include <ctime> 

using namespace std; 
int main() { 
  srand( (char)time(0)); // Seed the random number generator
  char userChoice,
       computerChoice;
  int r; // Random number generated by the conputer

  cout << "Welcome to the Rock, Paper, Scissors Game!\n" << endl; 
  for (int i = 0; i < 5; i++) // Loop 5 times
  {
    cout << "Round " << i+1 << endl; // Display the round number

    cout << "Human Player: Rock (R or r), Paper(P or p) or Scissors(S or s): "; 
    cin >> userChoice; // my choice 
    userChoice = toupper(userChoice);
    switch (userChoice) // only for the human player 
    {
      case 'R': 
      case 'r':
      break;
      case 'P': 
      case 'p':
      break;
      case 'S':
      case 's':
      break; 
      default: cout << "Try again. Enter R, r, P, p, S, or s.\n" << endl; // if input is not R, r, P, p, S, or s, display error message
    }
    char choice[] = {'R','P', 'S'}; // Array of choices
    r = rand() % 3; // Generate a random number between 0 and 3
    computerChoice = choice[r]; // Assign the computer's choice to the computerChoice variable
    cout << "Computer Choice: " << computerChoice << endl; // the computers choice 
    switch (computerChoice) // only for player2
      {
        case 'R':
        case 'r': // inputing this will result in one of the condiitons
          // conditions only ture within the break 
          if (userChoice == 'R' || userChoice == 'r') // conditions
            cout << "It's a tie!\n" << endl;
          else if (userChoice == 'S' || userChoice == 's')
            cout << "Computer wins!\n" << endl; 
          else if (userChoice == 'P' || userChoice == 'p')
            cout << "Human Player wins!\n" << endl;
        break; 

        case 'P':
        case 'p': // inputing this will result in one of the conditions
          if (userChoice == 'P' || userChoice == 'p') // conditions
            cout << "It's a tie!\n" << endl;
          else if (userChoice == 'R' || userChoice == 'r')
            cout << "Computer wins!\n" << endl;
          else if (userChoice == 'S' || userChoice == 's')
            cout << "Human Player wins!\n" << endl;
        break;

        case 'S':
        case 's': // inputing this will result in one of the conditions
          if (userChoice == 'S' || userChoice == 's') // conditions
            cout << "It's a tie!\n" << endl;
          else if (userChoice == 'P' || userChoice == 'p')
            cout << "Computer wins!\n" << endl;
          else if (userChoice == 'R' || userChoice == 'r')
            cout << "Human Player wins!\n" << endl;
        break; 

        default: cout << "Try again. Enter R, r, P, p, S, or s.\n" << endl; // if input is not R, r, P, p, S, or s, display error message
        }

  }

}